#spring.application.name=e-com
  server:
    port: 8189
    servlet:
      context-path: /market
  spring:
    datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:mem:mydatabase;MODE=PosgreSQL
      username: sa
      password:
    jpa:
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.H2Dialect
    h2:
      console:
        enables: true
        settings:
          web-allow-others: false